### ISSUE TITLE
Authors are shown as vsts on nuget.org

### ISSUE THREAD

**Issue by Arash-Sabet** [SimcoeAI/xunittools#10]
**Describe the bug**
Authors are shown as vsts on nuget.org despite the csproj file contains the necessary metadata. The issue could be originated from the build pipeline's yaml file.

**Expected behavior**
We need to display the authors' name on nuget.org

**Screenshots**
![image](https://user-images.githubusercontent.com/26050123/96816913-2f32cc80-13ec-11eb-9bc3-7860e40a8c56.png)

**Comment by mghafoori** [comment]
Looking into it...

**Comment by mghafoori** [comment]
I tried different things in the pipeline with no success. Creating a new nuget.org token and using it in the pipeline may fix the issue. @Arash-Sabet can you create a new token and try it to see if it works?

**Comment by Arash-Sabet** [comment]
@mghafoori I will look into it. thanks.

**Comment by Arash-Sabet** [comment]
@mghafoori The issue resolved by adding a nuspec file to the project's folder.
