### ISSUE TITLE
Test project's build yaml file is required

### ISSUE THREAD

**Issue by Arash-Sabet** [SimcoeAI/xunittools#3]

**Comment by Arash-Sabet** [comment]
@mghafoori would you please take a look at the build yaml file to figure out why it wouldn't publish the nuget package to nuget.org despite the credentials are set up right? Thanks.

Further info:

> 2020-10-21T02:33:20.1638453Z Using authentication information for the following URI: https://api.nuget.org/v3/index.json
> 2020-10-21T02:33:20.1689396Z ##[error]Error: DotNetCore currently does not support using an encrypted Api Key.
> 2020-10-21T02:33:20.1714717Z ##[error]Packages failed to publish
> 2020-10-21T02:33:20.1716891Z Info: Azure Pipelines hosted agents have been updated to contain .Net Core 3.x (3.1) SDK/Runtime along with 2.1. Unless you have locked down a SDK version for your project(s), 3.x SDK might be picked up which might have breaking behavior as compared to previous versions. 
> 2020-10-21T02:33:20.1717747Z Some commonly encountered changes are: 
> 2020-10-21T02:33:20.1719843Z If you're using `Publish` command with -o or --Output argument, you will see that the output folder is now being created at root directory rather than Project File's directory. To learn about more such changes and troubleshoot, refer here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting
> 2020-10-21T02:33:20.1723085Z ##[section]Finishing: DotNetCoreCLI

**Comment by Arash-Sabet** [comment]
Closing this issue as @mghafoori addressed the build yaml file in [this code commitment](https://github.com/SimcoeAI/xunittools/commit/31892052efdf9d273d46cbe7f3ead0fc6779711d).

**Comment by mghafoori** [comment]
It looks like a known issue:
https://github.com/Microsoft/azure-pipelines-tasks/issues/7160
So I switched to NuGetCommand and it worked. I remember I dealt with this before, and I find it a bit annoying that DotNetCore command is not able to handle it.

**Comment by Arash-Sabet** [comment]
@mghafoori Interesting! a good point to consider for other build pipelines.
